Add siteplan implementation
eclipse-set/set pull request #101
Opened 2023-09-28 07:16 UTC by pstuecker

This adds the siteplan component used for visualizing the planning data contained in a .planpro file. It also integrates a small developer help which helps in configuring various parameters (e.g. default zoom level) for the siteplan. 

## Note

As this is a large change with more than 1000 lines, we require an additional IP Review per the Eclipse Development Process.

2023-09-28 08:37 UTC, pstuecker commented
/license-check

2023-09-28 09:05 UTC, pstuecker commented
/license-check

2023-09-28 09:21 UTC, pstuecker commented
/license-check

2023-09-28 10:40 UTC, pstuecker commented
/license-check

2023-09-28 10:51 UTC, pstuecker commented
/request-license-review

2023-10-09 05:13 UTC, pstuecker commented
/license-check

2023-10-09 05:38 UTC, pstuecker commented
Project content review requested at https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10949

2023-10-09 08:15 UTC, pstuecker commented
/license-check

2023-10-25 13:23 UTC, pstuecker commented
Project content has been approved https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10949

This should be merged after 2.1.0 is released

2023-11-01 13:26 UTC, TruongQuangSB requested changes

2023-11-02 08:05 UTC, TruongQuangSB approved these changes

2023-11-02 08:06 UTC, merged