Lint: Migration to Stylistic
eclipse-set/set pull request #1016
Opened 2024-10-28 10:00 UTC by TruongQuangSB

https://eslint.style/guide/why

2024-11-11 14:17 UTC, mariusheine requested changes

2024-11-11 14:17 UTC, mariusheine commented on web/siteplan/src/util/MapSources/MapboxTop.ts
> +  source: VectorTileSource|null = null
@TruongQuangSB Weird formatting. I would keep the spaces

2024-11-11 14:17 UTC, mariusheine commented on web/siteplan/src/util/MapSources/MapboxTop.ts
> +    const sourceId = Object.keys(style.sources)[ 0 ]
@TruongQuangSB Here I would stay with no spaces around the `0`

2024-11-11 14:17 UTC, mariusheine commented on web/textviewer/package.json
> +    "@stylistic/eslint-plugin": "2.8.0",
@TruongQuangSB Same here as in package.json of siteplan

2024-11-11 14:17 UTC, mariusheine commented on web/siteplan/.eslintrc.cjs
> +    'no-console': process.env.NODE_ENV === 'production' ? ['warn', {allow: ['warn', 'error']}] : 'off',
@TruongQuangSB Here I would stay with spaces...

2024-11-12 11:45 UTC, TruongQuangSB commented on web/siteplan/package.json
> -    "eslint": "^9.12.0",
@mariusheine here used the `stylistic` as plugins to lint parse and this package already contained `eslint`

2024-11-12 15:49 UTC, mariusheine commented on web/siteplan/package.json
> -    "eslint": "^9.12.0",
@TruongQuangSB But it only has it as peer dependencies... https://www.npmjs.com/package/@stylistic/eslint-plugin?activeTab=dependencies

When you look at their github repo you see that it has it only as peer dependency: https://github.com/eslint-stylistic/eslint-stylistic/blob/main/packages/eslint-plugin/package.json

that's why I am pretty confused...

2024-11-22 16:00 UTC, TruongQuangSB commented on web/siteplan/package.json
> -    "eslint": "^9.12.0",
ok, u are right

2024-11-25 10:37 UTC, mariusheine approved these changes
@TruongQuangSB One last thing :smile:

2024-11-25 10:37 UTC, mariusheine commented on web/textviewer/src/app.ts
> +  pendingSetLine: number|null = null
@TruongQuangSB At other locations we have spaces between the pipe

2024-11-25 13:11 UTC, TruongQuangSB commented on web/textviewer/src/app.ts
> +  pendingSetLine: number|null = null
@mariusheine it given't rule no space before and after the pipe by type annotation. We must check manuael 😄

2024-11-26 11:33 UTC, mariusheine approved these changes

2024-11-26 11:34 UTC, merged