Fix find banking line process
eclipse-set/set pull request #1118
Opened 2024-12-02 13:37 UTC by TruongQuangSB

2024-12-09 15:24 UTC, mariusheine requested changes

2024-12-09 15:24 UTC, mariusheine commented on java/bundles/org.eclipse.set.basis/src/org/eclipse/set/basis/graph/TopPath.java
> +			final BigDecimal firstEdgeLength) {
@TruongQuangSB This constructor is also used in `DirectedPathSearch.java`. Do we need to adjust something there accordingly?

2024-12-09 15:24 UTC, mariusheine commented on java/bundles/org.eclipse.set.feature.plazmodel/src/org/eclipse/set/feature/plazmodel/check/BankValues.xtend
> +					"Die Überhöhungslinie {GUID} fehlt Ueberhoehung_A oder Ueberhoehung_B.",
```suggestion
					"Die Überhöhungslinie {GUID} hat entweder keine Ueberhoehung_A oder keine Ueberhoehung_B.",
```

2024-12-09 15:24 UTC, mariusheine commented on java/bundles/org.eclipse.set.utils/src/org/eclipse/set/utils/graph/AsDirectedTopGraph.java
> -				final Node edgeSource = graph.getEdgeSource(edge);
@TruongQuangSB Is there any particular reason why you have moved this line up? Any internal assertions?

2024-12-09 15:24 UTC, mariusheine commented on java/bundles/org.eclipse.set.utils/src/org/eclipse/set/utils/graph/AsDirectedTopGraph.java
> +				// replace the weight
```suggestion
				// When another edge exists, which is shorter than found edge, replace the weight
```

2024-12-09 16:35 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.basis/src/org/eclipse/set/basis/graph/TopPath.java
> +			final BigDecimal firstEdgeLength) {
@mariusheine y, u are right. This should be also modified

2024-12-10 12:37 UTC, mariusheine approved these changes

2024-12-10 12:38 UTC, merged