Ssks: Find route km throught projection of signal on route
eclipse-set/set pull request #1134
Opened 2024-12-06 17:08 UTC by TruongQuangSB

2025-02-04 11:03 UTC, mariusheine requested changes

2025-02-04 11:03 UTC, mariusheine commented on java/bundles/org.eclipse.set.application/src/org/eclipse/set/application/geometry/GeoKanteGeometryServiceImpl.java
> +			final BigDecimal projectionTopDistance = getCoordinateTopDistance(
@TruongQuangSB We should name it generically here now

```suggestion
			// Determine topological distance from start of object to the
			// projection
			final BigDecimal projectionDistance = getCoordinateTopDistance(
```

2025-02-04 11:03 UTC, mariusheine commented on java/bundles/org.eclipse.set.application/src/org/eclipse/set/application/geometry/GeoKanteGeometryServiceImpl.java
> +					object.getIdentitaet().getWert());
@TruongQuangSB Here as well more generically

```suggestion
			logger.error(
					"Can\'t find projection of Coordinate: ({}, {}) on object {} {}", //$NON-NLS-1$
					Double.valueOf(coordinate.x), Double.valueOf(coordinate.y),
					object.getClass().getName(),
					object.getIdentitaet().getWert());
```

2025-02-04 11:03 UTC, mariusheine commented on java/bundles/org.eclipse.set.application/src/org/eclipse/set/application/geometry/GeoKanteGeometryServiceImpl.java
>  	 *            the TOP_Kante
@TruongQuangSB Wrong java doc. Maybe should also rename it also to just `object`

2025-02-04 11:03 UTC, mariusheine commented on java/bundles/org.eclipse.set.application/src/org/eclipse/set/application/geometry/GeoKanteGeometryServiceImpl.java
> +	private static BigDecimal getScalingFactor(final Basis_Objekt geoArt)
@TruongQuangSB Here as well. Rename `geoArt` and update all comments to not be based on top kante anymore

2025-02-04 11:46 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.feature.siteplan/src/org/eclipse/set/feature/siteplan/transform/TrackTransformator.xtend
> +						geoKante, getCRS(knotenB)));
@mariusheine y, u are right

2025-02-04 14:01 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.application/src/org/eclipse/set/application/geometry/GeoKanteGeometryServiceImpl.java
> +					object.getIdentitaet().getWert());
@mariusheine the object here can only TOP_Kante or Strecke

2025-02-05 10:21 UTC, mariusheine approved these changes

2025-02-05 10:22 UTC, merged