Implementation ESTW Supplement Table: Sskz
eclipse-set/set pull request #1148
Opened 2024-12-11 10:35 UTC by TruongQuangSB

2024-12-11 11:22 UTC, mariusheine requested changes

2024-12-11 11:22 UTC, mariusheine commented on java/bundles/org.eclipse.set.basis/src/org/eclipse/set/basis/constants/ToolboxConstants.java
> +	 * The prefix of ETCS Supplement table part
```suggestion
	 * The prefix of ESTW Supplement table part
```

2024-12-11 11:22 UTC, mariusheine commented on java/bundles/org.eclipse.set.basis/src/org/eclipse/set/basis/constants/ToolboxConstants.java
> +	public static final String ESTW_SUPPLEMENT_PART_ID_PREFIX = "org.eclipse.set.feature.table.supplement-estw";
```suggestion
	public static final String ESTW_SUPPLEMENT_PART_ID_PREFIX = "org.eclipse.set.feature.table.estw-supplement";
```

Better readability in my opinion and from a sorting perspective estw and estw-supplement are next to each other then

2024-12-11 11:22 UTC, mariusheine commented on java/bundles/org.eclipse.set.basis/src/org/eclipse/set/basis/constants/ToolboxConstants.java
> +	public static final String ESTW_SUPPLEMENT_CATEGORY = "supplement-estw";
```suggestion
	public static final String ESTW_SUPPLEMENT_CATEGORY = "est-supplement";
```

2024-12-11 11:22 UTC, mariusheine commented on java/bundles/org.eclipse.set.feature.table.pt1/src/org/eclipse/set/feature/table/pt1/sskz/SskzTransformator.java
> +				.filterObjectsInControlArea(outsideControl, controlArea);
```suggestion
		final List<Aussenelementansteuerung> outsideControls = Streams
				.stream(container.getAussenelementansteuerung())
				.filter(UrObjectExtensions::isPlanningObject).toList();
		final Iterable<Aussenelementansteuerung> relevantControlsInArea = UrObjectExtensions
				.filterObjectsInControlArea(outsideControls, controlArea);
```

2024-12-11 11:22 UTC, mariusheine commented on java/bundles/org.eclipse.set.feature.table/OSGI-INF/l10n/bundle.properties
> +ESTW_Supplement_TableOverviewDescriptionService_ViewName=ESTW – Zusatzttabellen – Tabellenübersicht
```suggestion
ESTW_Supplement_TableOverviewDescriptionService_ViewName=ESTW – Zusatztabellen – Tabellenübersicht
```

2024-12-11 11:22 UTC, mariusheine commented on java/bundles/org.eclipse.set.feature.table/src/org/eclipse/set/feature/table/messages/Messages.java
> +	 * ESTW – Zusatzttabellen – Tabellenübersicht
```suggestion
	 * ESTW – Zusatztabellen – Tabellenübersicht
```

2024-12-11 11:22 UTC, mariusheine commented on java/bundles/org.eclipse.set.utils/src/org/eclipse/set/utils/viewgroups/Messages.java
> +	public static String SetViewGroups_Table_ETCW_Supplement;
```suggestion
	public static String SetViewGroups_Table_ESTW_Supplement;
```

2024-12-11 11:22 UTC, mariusheine commented on java/bundles/org.eclipse.set.utils/src/org/eclipse/set/utils/viewgroups/messages.properties
> +SetViewGroups_Table_ETCW_Supplement= ESTW \u2013 Zusatztabellen
```suggestion
SetViewGroups_Table_ESTW_Supplement= ESTW \u2013 Zusatztabellen
```

2024-12-11 11:29 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.basis/src/org/eclipse/set/basis/constants/ToolboxConstants.java
> +	public static final String ESTW_SUPPLEMENT_PART_ID_PREFIX = "org.eclipse.set.feature.table.supplement-estw";
@mariusheine At the moment use we String.startWith({TABLE_PREFIX) to find, which Category the Table belong to. Because of this when use `estw-supplement`, then the Table of ESTW Supplement will belong to ESTW 😄

2024-12-11 11:30 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.utils/src/org/eclipse/set/utils/viewgroups/SetViewGroups.java
> +				.withText(Messages.SetViewGroups_Table_ETCW_Supplement)
```suggestion
				.withText(Messages.SetViewGroups_Table_ESTW_Supplement)
```

2024-12-11 13:06 UTC, mariusheine commented on java/bundles/org.eclipse.set.basis/src/org/eclipse/set/basis/constants/ToolboxConstants.java
> +	public static final String ESTW_SUPPLEMENT_PART_ID_PREFIX = "org.eclipse.set.feature.table.supplement-estw";
@TruongQuangSB Ok then it makes sense to have it like this :smile:

2024-12-11 13:07 UTC, mariusheine commented on java/bundles/org.eclipse.set.basis/src/org/eclipse/set/basis/constants/ToolboxConstants.java
> +	public static final String ESTW_SUPPLEMENT_CATEGORY = "supplement-estw";
Obsolete. see https://github.com/eclipse-set/set/pull/1148#discussion_r1879921667

2024-12-11 13:08 UTC, mariusheine commented on java/bundles/org.eclipse.set.feature.table/OSGI-INF/l10n/bundle.properties
> +ESTW_Supplement_TableOverviewDescriptionService_ViewName=ESTW – Zusatzttabellen – Tabellenübersicht
@TruongQuangSB You missed this one

2024-12-11 13:09 UTC, mariusheine commented on java/bundles/org.eclipse.set.feature.table.pt1/src/org/eclipse/set/feature/table/pt1/sskz/SskzTransformator.java
> +				.filterObjectsInControlArea(outsideControl, controlArea);
@TruongQuangSB And what about this one? Just making the variable plural.

2024-12-12 09:14 UTC, mariusheine approved these changes

2024-12-12 09:14 UTC, merged