Fix missing railway by development mode
eclipse-set/set pull request #1179
Opened 2024-12-16 17:01 UTC by TruongQuangSB

2025-01-08 16:07 UTC, mariusheine requested changes

2025-01-08 16:07 UTC, mariusheine commented on web/siteplan/src/feature/TrackFeature.ts
> +  protected createCompareFeatures (initial: SiteplanState, final: SiteplanState): Feature<Geometry>[] {
@TruongQuangSB So the actual bug was that the default compare feature calculation was not suitable for tracks, correct?

2025-01-08 16:07 UTC, mariusheine commented on web/siteplan/src/feature/TrackFeature.ts
> +        result.push(initialFeature)
@TruongQuangSB Do we really need to push the initialFeature if we have found a final feature? Or is the initial feature the one painted in red in the siteplan?

2025-01-08 16:16 UTC, TruongQuangSB commented on web/siteplan/src/feature/TrackFeature.ts
> +  protected createCompareFeatures (initial: SiteplanState, final: SiteplanState): Feature<Geometry>[] {
correct

2025-01-08 16:16 UTC, TruongQuangSB commented on web/siteplan/src/feature/TrackFeature.ts
> +        result.push(initialFeature)
when the inital and the final state aren't same, then we need add both feature to visual change. Also:
- red is final
- yellow is initial

2025-01-08 16:16 UTC, TruongQuangSB commented on web/siteplan/src/feature/TrackFeature.ts
> +  }
ok

2025-01-08 16:25 UTC, mariusheine commented on web/siteplan/src/feature/TrackFeature.ts
> +        result.push(initialFeature)
@TruongQuangSB 🙈 Yes initial is yellow...

And we only find a `finalFeature` if there are differences? Or where do we checked if intial and final aren't same?

2025-01-08 16:31 UTC, TruongQuangSB commented on web/siteplan/src/feature/TrackFeature.ts
> +        result.push(initialFeature)
y, the `finalFeature` will only by differences to `result` added 
It was compare in line 354, the variable name isn't correct. `finalFeautre` should be `changed` or `isEqual`

2025-01-08 16:35 UTC, mariusheine commented on web/siteplan/src/feature/TrackFeature.ts
> +        result.push(initialFeature)
@TruongQuangSB Alright then it looks fine. Can you please change the variable accordingly then?

2025-01-08 16:45 UTC, TruongQuangSB commented on web/siteplan/src/feature/TrackFeature.ts
> +        result.push(initialFeature)
ok

2025-01-10 10:18 UTC, mariusheine requested changes

2025-01-10 10:18 UTC, mariusheine commented on web/siteplan/src/feature/TrackFeature.ts
> +    const exsitDiffSection = initialTracks.some(initialTrack => {
@TruongQuangSB A small typo

```suggestion
    const existDiffSection = initialTracks.some(initialTrack => {
```

2025-01-10 10:18 UTC, mariusheine commented on web/siteplan/src/feature/TrackFeature.ts
> +    return isDiffDesignation || exsitDiffSection
```suggestion
    return isDiffDesignation || existDiffSection
```

2025-01-10 12:29 UTC, mariusheine approved these changes

2025-01-10 12:41 UTC, merged