Enable project data editor and create new project
eclipse-set/set pull request #151
Opened 2023-11-03 09:16 UTC by TruongQuangSB

2023-11-06 06:50 UTC, pstuecker commented
The project data view has a few issues:

- The Gruppe/Einzelplanung tab control is hardly visible. 
- Scrolling via mouse wheel does not work
- Saving the changed file causes a UI freeze (due to validations being run)
- Also opening the view edit view takes a lot of time

2023-11-06 06:57 UTC, pstuecker requested changes
The project data view has a few issues:

- The Gruppe/Einzelplanung tab control is hardly visible.
- Scrolling via mouse wheel does not work
- Saving the changed file causes a UI freeze (due to validations being run)
- Also opening the view edit view takes a lot of time

For newly created files:

- If Name is not filled, the button "Aus Name ableiten" throws an IllegalArgumentException (same in Einzelplanung)
- Changing the "Abschluss"-Date and then confirming the dialog throws a ClassCastException
- LST_Planung/Fachdaten/Ausgabe_Fachdaten/Untergewerk_Art is nil-filled, but shows in the UI as ESTW.

2023-11-07 11:18 UTC, TruongQuangSB commented
The project data view has a few issues:
- ~~The Gruppe/Einzelplanung tab control is hardly visible.~~  :white_check_mark:
- ~~Scrolling via mouse wheel does not work~~ :white_check_mark:
- ~~Saving the changed file causes a UI freeze (due to validations being run)~~ :white_check_mark: it will be showing process dialog when saving
- ~~Also opening the view edit view takes a lot of time~~ :white_check_mark: it will only rendere selectec tab when it open part (previously total tab view will be rendere by open part)

For newly created files:
- ~~If Name is not filled, the button "Aus Name ableiten" throws an IllegalArgumentException (same in Einzelplanung)~~ :white_check_mark: button will be disable, when Name empty
- ~~Changing the "Abschluss"-Date and then confirming the dialog throws a ClassCastException~~ :white_check_mark:
- ~~LST_Planung/Fachdaten/Ausgabe_Fachdaten/Untergewerk_Art is nil-filled, but shows in the UI as ESTW.~~ TabName take another object (LST_Planung/Objektmanagement/LST_Planung_Projekt/LST_Planung_Gruppe/Planung_G_Allg/Untergewerk_Art)

2023-11-10 12:45 UTC, pstuecker approved these changes

2023-11-10 12:45 UTC, merged