Implementation Sskp
eclipse-set/set pull request #21
Opened 2023-08-18 10:03 UTC by TruongQuangSB

- Implementation PZB Table Sskp in 1.10

2023-09-05 07:54 UTC, pstuecker requested changes

2023-09-05 07:58 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.feature.table.pt1/src/org/eclipse/set/feature/table/pt1/sskp/SskpTransformator.xtend
> +					].filter[it == 0.0].map[it.toString]
you are right, my mistake

2023-09-05 07:59 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.feature.table.pt1/src/org/eclipse/set/feature/table/pt1/sskp/SskpTransformator.xtend
> +					].filter[it == 0.0].map[it.toString]
´
```suggestion
					].filter[it !== 0.0].map[it.toString]
```

2023-09-06 09:20 UTC, pstuecker approved these changes

2023-09-06 09:20 UTC, merged