Active disable Unittest
eclipse-set/set pull request #23
Opened 2023-08-23 12:04 UTC by TruongQuangSB

- Active toolboxfile test with test file of model version 1.10

2023-08-23 12:05 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.unittest.utils/src/org/eclipse/set/unittest/utils/AbstractToolboxTest.java
> -			"PPHN_01-02_Ibn-Z.-2.AeM_2022-07-26_16-36.ppxml"); //$NON-NLS-1$
delete old test file

2023-08-24 12:04 UTC, pstuecker requested changes

2023-08-24 12:04 UTC, pstuecker commented on java/bundles/org.eclipse.set.core.test/src/org/eclipse/set/core/fileservice/PlainToolboxFileTest.xtend
> +	static val TESTPATH = ""
We should use an unpacked PPHN file here

2023-08-24 12:22 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.core.test/src/org/eclipse/set/core/fileservice/PlainToolboxFileTest.xtend
> +	static val TESTPATH = ""
ok

2023-08-24 12:35 UTC, pstuecker approved these changes

2023-08-24 12:36 UTC, merged