Overviewplan: Track Transform
eclipse-set/set pull request #235
Opened 2023-11-29 10:59 UTC by TruongQuangSB

- The [PR#206](https://github.com/eclipse-set/set/pull/206) should be merge first.
- Add Track Transformator:
  - Currently the transformator only find out the overview track, which contains a lot TOPKanten that represent a straight line in the Overviewplan

2024-02-22 05:37 UTC, pstuecker requested changes
still need to review 

- TrackTransformator.xtend
- TrackServiceImpl.xtend
- TOPKanteMetaData.xtend

2024-02-22 05:37 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.export/OSGI-INF/l10n/bundle.properties
> +SiteplanModelExportDescriptionService_ViewName=Lageplan und Uebersichtplan Modell Export
```suggestion
SiteplanModelExportDescriptionService_ViewName=Lageplan und Übersichtsplan Modell Export
```

2024-02-22 05:37 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.export/src/org/eclipse/set/feature/export/descriptions/SiteplanModelExportDescriptionService.java
> +/**
Outdated license header

2024-02-22 05:37 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.overviewplan.test/src/org/eclipse/set/feature/overviewplan/transformator/OverviewplanTransformatorTest.java
> + * Copyright (c) 2023 DB Netz AG and others.
Outdated license header

2024-02-22 05:37 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.export/src/org/eclipse/set/feature/export/parts/SiteplanModelExportPart.java
> + * Copyright (c) 2023 DB Netz AG and others.
Outdated license header

2024-02-22 05:37 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.overviewplan.test/src/org/eclipse/set/feature/overviewplan/transformator/OverviewplanTransformatorTest.java
> +	private void whenTransformingToSiteplanModel() {
```suggestion
	private void whenTransformingToOverviewplanModel() {
```

2024-02-22 05:37 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.overviewplan/OSGI-INF/l10n/bundle.properties
> +WebOverviewplanDescriptionService_ViewName=Su (Sicherungstechnischer �bersichtplan)
```suggestion
WebOverviewplanDescriptionService_ViewName=Su (Sicherungstechnischer �bersichtsplan)
```

2024-02-22 05:37 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.overviewplan/src/org/eclipse/set/feature/overviewplan/Messages.java
> + * Copyright (c) 2023 DB Netz AG and others.
Outdated license header

2024-02-22 05:37 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.overviewplan/src/org/eclipse/set/feature/overviewplan/parts/WebOverviewplanPart.java
> + * Copyright (c) 2023 DB Netz AG and others.
Outdated license header

2024-02-22 05:37 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.overviewplan/src/org/eclipse/set/feature/overviewplan/track/OverviewplanTrack.java
> + * Copyright (c) 2023 DB Netz AG and others.
Outdated license header

2024-02-22 05:37 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.overviewplan/src/org/eclipse/set/feature/overviewplan/track/TOPKanteMetaData.xtend
> + * Copyright (c) 2023 DB Netz AG and others.
Outdated license header

2024-02-22 05:37 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.overviewplan/src/org/eclipse/set/feature/overviewplan/track/TOPKanteMetaData.xtend
> +			throw new IllegalArgumentException('''TOP_Knoten: «topNode.identitaet.wert» gehört nicht zu TOP_Katen: «topEdge.identitaet.wert»''')
Exceptions should be in English

2024-02-22 05:37 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.overviewplan/src/org/eclipse/set/feature/overviewplan/track/TrackService.java
> + * Copyright (c) 2023 DB Netz AG and others.
Outdated license header

2024-02-22 05:37 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.overviewplan/src/org/eclipse/set/feature/overviewplan/track/TrackServiceImpl.xtend
> + * Copyright (c) 2023 DB Netz AG and others.
Outdated license header

2024-02-22 05:37 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.overviewplan/src/org/eclipse/set/feature/overviewplan/transformator/OverviewplanTransformator.java
> + * Copyright (c) 2023 DB Netz AG and others.
Outdated license header

2024-02-22 05:37 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.overviewplan/src/org/eclipse/set/feature/overviewplan/transformator/OverviewplanTransformatorImpl.java
> + * Copyright (c) 2023 DB Netz AG and others.
Outdated license header

2024-02-22 05:37 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.overviewplan/src/org/eclipse/set/feature/overviewplan/transformator/TrackTransformator.xtend
> + * Copyright (c) 2023 DB Netz AG and others.
Outdated license header

2024-02-22 05:37 UTC, pstuecker commented on java/bundles/org.eclipse.set.ppmodel.extensions/src/org/eclipse/set/ppmodel/extensions/GeoKanteExtensions.xtend
> +				throw new IllegalArgumentException('''GEOKnoten: «geoKnoten.identitaet.wert» gehört nicht zu GEOKanten: «geoKante.identitaet.wert»''')
Exception message should be in English

2024-02-22 05:37 UTC, pstuecker commented on java/bundles/org.eclipse.set.ppmodel.extensions/src/org/eclipse/set/ppmodel/extensions/TopKanteExtensions.xtend
> +			throw new IllegalArgumentException('''Auf TOP_Kante: «topKante.identitaet.wert» verweiss TOP_Knoten: «topKnoten.identitaet.wert» auf mehr als ein GEO_Kante''')
Exception should be in English

2024-02-22 05:37 UTC, pstuecker commented on java/bundles/org.eclipse.set.ppmodel.extensions/src/org/eclipse/set/ppmodel/extensions/WKrGspKomponenteExtensions.xtend
> +	def static List<TOP_Kante> getTOPKante(W_Kr_Gsp_Komponente komponente) {
This should be part of Punkt_Objekt Extensions

2024-02-22 05:37 UTC, pstuecker commented on java/bundles/org.eclipse.set.utils/src/org/eclipse/set/utils/collection/MapExtensions.xtend
> + * Copyright (c) 2023 DB Netz AG and others.
Outdated license header

2024-02-26 06:47 UTC, pstuecker requested changes
In general it's very hard to follow the data flows from the model to the overview plan model

2024-02-26 06:47 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.overviewplan/src/org/eclipse/set/feature/overviewplan/transformator/TrackTransformator.xtend
> +		if (state.tracks.flatMap[sections].exists [
this should be checked before the track is created

2024-02-26 06:47 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.overviewplan/src/org/eclipse/set/feature/overviewplan/transformator/TrackTransformator.xtend
> +		]
```suggestion
		val md = trackService.getTOPKanteMetaData(topKante)
		track.transformSection(md, md.topNodeA)
		track.transformSection(md, md.topNodeB)

```

2024-02-26 06:47 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.overviewplan/src/org/eclipse/set/feature/overviewplan/track/TrackServiceImpl.xtend
> +	private def TOPKanteMetaData getCache(String guid) {
getMetadata? this does not return a cache

2024-02-26 06:47 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.overviewplan/src/org/eclipse/set/feature/overviewplan/track/TrackServiceImpl.xtend
> +			return cache.getIfPresent(guid) as TOPKanteMetaData
using the guid as key does not work, as edges from initial/target states have the same guids

2024-02-26 06:47 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.overviewplan/src/org/eclipse/set/feature/overviewplan/track/TrackServiceImpl.xtend
> +		val md = container.TOPKante.get(0).TOPKanteMetaData
If there's no TOP_Kante in the model, get(0) throws

2024-02-26 06:47 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.overviewplan/src/org/eclipse/set/feature/overviewplan/track/TrackServiceImpl.xtend
> +	override setupTrackNetz(MultiContainer_AttributeGroup container) {
```suggestion
	override setupTrackNet(MultiContainer_AttributeGroup container) {
```

2024-02-26 06:47 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.overviewplan/src/org/eclipse/set/feature/overviewplan/track/TOPKanteMetaData.xtend
> +	TrackService trackService
the metadata for a geo kante should not contain a trackService

2024-02-26 06:47 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.overviewplan/src/org/eclipse/set/feature/overviewplan/track/TrackServiceImpl.xtend
> +	static Map<String, TOPKanteMetaData> metadataCache = newHashMap
do these need to be static?

2024-02-26 06:47 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.overviewplan/src/org/eclipse/set/feature/overviewplan/track/TrackServiceImpl.xtend
> +		return topKanten.map[TOPKanteMetaData]
```suggestion
		return topKnoten.topKanten.map[TOPKanteMetaData]
```

2024-02-26 07:45 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.feature.overviewplan/src/org/eclipse/set/feature/overviewplan/transformator/OverviewplanTransformatorImpl.java
> +		trackService.setupTrackNetz(container);
```suggestion
		trackService.setupTrackNet(container);
```

2024-02-26 10:05 UTC, pstuecker requested changes

2024-02-26 11:51 UTC, pstuecker approved these changes

2024-02-26 11:52 UTC, merged