Improve topological graph finding
eclipse-set/set pull request #320
Opened 2024-01-15 14:20 UTC by pstuecker

This PR introduces a new TopologicalGraphService based on JGraphT for finding  distances between points on the topological track graph.

Compared to our existing Digraphs/TopRouting implementation this grants us the following benefits:

- Performance is significantly better (~20% speed up for PPHN Sskp generation)
- The TOPGraph is kept during a session rather than recreating the graph multiple times
- We can search for arbitrary points on a TopEdge (TopRouting only allows to search for point objects). 

Limitations:

- Currently there is no support for the point object path iterator, so we can't remove the Digraph implementation yet. 

The new graph service is now being used for most relevant tables as well as for a new implementation for the Sskp Bahnsteig<-> PZB distances.

This also fixes an old issue with the CacheService not being usable from OSGi services.

2024-01-15 15:30 UTC, pstuecker commented
/license-check

2024-02-01 13:58 UTC, TruongQuangSB requested changes

2024-02-01 13:58 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.feature.table.pt1/src/org/eclipse/set/feature/table/pt1/sskp/SskpBahnsteigUtils.java
> +		final double limitB = botb.getBegrenzungA().getWert().doubleValue();
```suggestion
		final double limitB = botb.getBegrenzungB().getWert().doubleValue();
```

2024-02-05 09:29 UTC, pstuecker commented
Changes are applied in https://github.com/eclipse-set/set/pull/365

2024-02-05 10:37 UTC, TruongQuangSB approved these changes

2024-02-05 10:37 UTC, merged