Implement Import Model Function
eclipse-set/set pull request #407
Opened 2024-02-22 11:08 UTC by TruongQuangSB

In this PR:
- Implemenet import model function in development mode.
- At this moment the retarget reference ID function isn't working.
- After modification of model and retarget reference ID working should the import function in normal mode avaible

2024-02-22 12:07 UTC, TruongQuangSB commented
/license-check

2024-03-12 07:46 UTC, pstuecker commented
/license-check

2024-04-23 07:25 UTC, pstuecker approved these changes

2024-04-29 04:29 UTC, pstuecker requested changes

2024-04-29 04:29 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.projectdata/src/org/eclipse/set/feature/projectdata/ppimport/ImportControl.java
> +		SUBWORK,
ALL / FULL?

2024-04-29 04:29 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.projectdata/src/org/eclipse/set/feature/projectdata/ppimport/ImportControl.java
> +	PlanPro_Schnittstelle schnittstelle;
Should be private

2024-04-29 04:29 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.projectdata/src/org/eclipse/set/feature/projectdata/ppimport/ImportControl.java
> +	ImportComboFileField comboField;
Should be private

2024-04-29 04:29 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.projectdata/src/org/eclipse/set/feature/projectdata/ppimport/ImportControl.java
> +	Option option;
Should be private

2024-04-29 04:29 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.projectdata/src/org/eclipse/set/feature/projectdata/ppimport/ImportControl.java
> +public class ImportControl {
The control severely mixes logic with UI elements. Also the importing logic is separated into various files with a very unclear data flow (Parts in ImportControl, ModelImportUtils/PlanProImportPart).

2024-05-03 12:57 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.basis/src/org/eclipse/set/basis/constants/ValidationResult.java
> +	public static enum FileValidateState {
u are right, they are same

2024-05-24 08:49 UTC, pstuecker requested changes
- Changing the file after selecting a subwork allows pressing the import button and causing an exception.

2024-05-24 08:49 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.projectdata/OSGI-INF/l10n/bundle.properties
> +PlanProImportPart_importSubwork=PlanPro-Datei für Import neu Fachdaten auswählen
```suggestion
PlanProImportPart_importSubwork=PlanPro-Datei für Import von Fachdaten auswählen
```

2024-05-24 08:49 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.projectdata/OSGI-INF/l10n/bundle.properties
> +PlanproImportPart_Subwork_Notset=Fehl Untergewerk Art
```suggestion
PlanproImportPart_Subwork_Notset=Es wurde kein Untergewerk gewählt
```

2024-05-24 08:49 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.projectdata/OSGI-INF/l10n/bundle.properties
> +PlanProImportPart_ImportSameData=Sie haben dasselbe ausgewählen, Fachdaten oder Container zu importieren.Bitte ändern Sie die Auswahl.
```suggestion
PlanProImportPart_ImportSameData=Es kann nur ein Untergewerk pro Untergewerksart importiert werden.
```

2024-05-27 09:28 UTC, pstuecker approved these changes

2024-05-27 09:29 UTC, merged