Update to Eclipse 2023-12
eclipse-set/set pull request #422
Opened 2024-02-28 17:01 UTC by TruongQuangSB

2024-02-28 17:02 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.releng.target/org.eclipse.set.releng.target.target
> +			<unit id="javax.inject" version="0.0.0"/>
javax.inject still need for emf ecp

2024-02-28 17:16 UTC, TruongQuangSB commented
/license-check

2024-02-29 09:45 UTC, pstuecker requested changes

2024-02-29 09:45 UTC, pstuecker commented on java/bundles/org.eclipse.set.releng.target/org.eclipse.set.releng.target.target
>  		<location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="slicer" includeSource="true" type="InstallableUnit">
Xtend 2.34 is released and should be used instead

2024-02-29 10:26 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.releng.target/org.eclipse.set.releng.target.target
>  		<location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="slicer" includeSource="true" type="InstallableUnit">
ok

2024-02-29 11:06 UTC, merged