Stop Banking process, when find out the first result
eclipse-set/set pull request #445
Opened 2024-03-14 09:00 UTC by TruongQuangSB

2024-03-14 09:02 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.utils/src/org/eclipse/set/utils/ToolboxConfiguration.java
> +	private static final String BANK_LINE_TOP_PATH_OFFSET_LIMIT = "0.2"; //$NON-NLS-1$
we should reduce offset here for have the best result

2024-03-15 14:05 UTC, pstuecker requested changes

2024-03-15 14:05 UTC, pstuecker commented on java/bundles/org.eclipse.set.utils/src/org/eclipse/set/utils/graph/AsDirectedTopGraph.java
> +				final Node edgeSource = graph.getEdgeSource(edge);
In which case would the source vertex be needed?

2024-03-15 14:05 UTC, pstuecker commented on java/bundles/org.eclipse.set.utils/src/org/eclipse/set/utils/graph/DirectedPath.java
> +		final Node source = directedGraph.getEdgeSource(edges.get(0));
```suggestion
		final Node source = directedGraph.getEdgeSource(edges.getFirst());
```

2024-03-18 07:53 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.utils/src/org/eclipse/set/utils/graph/DirectedPath.java
> +public class DirectedPath {
ok

2024-03-18 07:54 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.utils/src/org/eclipse/set/utils/graph/AsDirectedTopGraph.java
> +				final int childDistance = weight
ur right, so is better

2024-03-18 08:04 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.utils/src/org/eclipse/set/utils/graph/AsDirectedTopGraph.java
> +				final Node edgeSource = graph.getEdgeSource(edge);
when the distance from target Vertex to this source vertex < max path weight, then mark this source vertex and continue find the relevant edges from this source vertex

2024-03-18 09:17 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.utils/src/org/eclipse/set/utils/graph/AsDirectedTopGraph.java
> +				final int childDistance = weight
ur right, so is better

2024-03-18 14:54 UTC, pstuecker approved these changes

2024-03-18 14:54 UTC, merged