Ssks: Update side distance
eclipse-set/set pull request #503
Opened 2024-04-10 15:00 UTC by TruongQuangSB

- Add distance from Signal to another track, when it is relevant

2024-04-10 15:03 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.ppmodel.extensions/src/org/eclipse/set/ppmodel/extensions/geometry/GEOKanteGeometryExtensions.java
> +	private static Map<GEO_Kante, LineString> edgeGeometry;
To improve preformance, should find geometry for geokante process execute only one time

2024-04-10 15:03 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.ppmodel.extensions/src/org/eclipse/set/ppmodel/extensions/geometry/GEOKanteGeometryExtensions.java
> +	}
like find BankingLine process, this process will be excecute in background after model complete load

2024-04-30 11:39 UTC, pstuecker commented on java/bundles/org.eclipse.set.ppmodel.extensions/src/org/eclipse/set/ppmodel/extensions/geometry/GEOKanteGeometryExtensions.java
> +	private static boolean isFindProcessComplete = false;
This shouldn't be static, as this is a service.

2024-04-30 11:40 UTC, pstuecker commented on java/bundles/org.eclipse.set.ppmodel.extensions/src/org/eclipse/set/ppmodel/extensions/geometry/GEOKanteGeometryExtensions.java
> +			findGeometryThread = new Thread(() -> {
isFindProcessComplete needs to be set to false again

2024-05-03 07:34 UTC, pstuecker requested changes

2024-05-03 07:34 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.table.pt1/src/org/eclipse/set/feature/table/pt1/ssks/SsksTransformator.xtend
> +			val distanceFromPoint = 7000 - Math.abs(seitlicherAbstand)
Should be a constant

2024-05-03 08:41 UTC, pstuecker requested changes

2024-05-03 08:41 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.siteplan/src/org/eclipse/set/feature/siteplan/trackservice/GEOKanteMetadata.xtend
> +		this.geometry = geoKante.getGeometry
```suggestion
		this.geometry = geoKante.geometry
```

2024-05-03 08:41 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.siteplan/src/org/eclipse/set/feature/siteplan/trackservice/GEOKanteMetadata.xtend
> +		this.geometry = geoKante.getGeometry
```suggestion
		this.geometry = geoKante.geometry
```

2024-05-03 08:41 UTC, pstuecker commented on java/bundles/org.eclipse.set.core.services/src/org/eclipse/set/core/services/cache/NoCacheService.java
> +		throw new UnsupportedOperationException();
```suggestion
		return Boolean.FALSE;
```

2024-05-03 08:41 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.siteplan/src/org/eclipse/set/feature/siteplan/transform/RouteTransformator.xtend
> +		positions.addAll(geoKante.getGeometry.
```suggestion
		positions.addAll(geoKante.geometry.
```

2024-05-03 09:06 UTC, pstuecker approved these changes

2024-05-03 09:06 UTC, merged