Implementation Jump from table to siteplan function
eclipse-set/set pull request #614
Opened 2024-05-24 08:12 UTC by TruongQuangSB

- Implementation Jump function from table (plaz, validate, planpro table) to siteplan.
- It is work like jump to source with right click on row, then selection menu item.
- When the select object doesn't guid reference, then the menu item will disable.
- If the selected object not exist in siteplan, then the menu item will disable. By not open siteplan, this check will not execute

2024-05-24 08:36 UTC, TruongQuangSB commented on web/siteplan/package.json
> +  "type": "module",
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated

2024-05-24 08:36 UTC, TruongQuangSB commented on web/siteplan/package.json
> +    "tslib": "^2.6.2",
Resolve lint warning

2024-05-28 06:23 UTC, pstuecker requested changes

2024-05-28 06:23 UTC, pstuecker commented on java/bundles/org.eclipse.set.application/OSGI-INF/l10n/bundle.properties
> +TableMenuService_Siteplan=Zeige in Siteplan
```suggestion
TableMenuService_Siteplan=Zeige in Lageplan
```

2024-05-28 06:24 UTC, pstuecker approved these changes

2024-05-28 06:24 UTC, merged