Improve error messages and infos in table overview
eclipse-set/set pull request #631
Opened 2024-05-30 09:14 UTC by mariusheine

The table overview (in debug mode) now looks like

![image](https://github.com/eclipse-set/set/assets/42845535/1ae62541-78de-435d-96c2-b7c13662918a)

2024-06-03 12:27 UTC, TruongQuangSB requested changes

2024-06-03 12:27 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.utils.table/src/org/eclipse/set/utils/table/TableDataProvider.xtend
> +		return tableContents.get(row).row.trueRowIndex
It will return wrong index of row, when the table change by filter or sort. Because the table, which reference for the row isn't change by filter and sort.

2024-06-05 07:35 UTC, mariusheine commented on java/bundles/org.eclipse.set.utils.table/src/org/eclipse/set/utils/table/TableDataProvider.xtend
> +		return tableContents.get(row).row.trueRowIndex
@TruongQuangSB But how did it worked then before, because the classical `rowIndex` is (almost) always 0 because it gives you the index inside the rowgroup and most of the groups only have one row.

I will test it in the `PlazModelTableView`. Or is there a better place to test it?

2024-06-05 08:08 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.utils.table/src/org/eclipse/set/utils/table/TableDataProvider.xtend
> +		return tableContents.get(row).row.trueRowIndex
do you have tested with sort and filter ? When i tested with both of them, then jump to wrong number

2024-06-05 08:17 UTC, mariusheine commented on java/bundles/org.eclipse.set.utils.table/src/org/eclipse/set/utils/table/TableDataProvider.xtend
> +		return tableContents.get(row).row.trueRowIndex
@TruongQuangSB Works for me also with a filter...

2024-06-05 12:21 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.feature.table/src/org/eclipse/set/feature/table/overview/TableErrorTableColumns.xtend
>  		root.add(LeadingObject).widthPercent(20)
```suggestion
		root.add(Source).widthPercent(5)
		root.add(TableType).widthPercent(10)
		root.add(RowNumber).widthPercent(5)
		root.add(LeadingObject).widthPercent(15)
```

2024-06-05 12:26 UTC, TruongQuangSB approved these changes

2024-06-05 13:14 UTC, merged