Plaz check for existence of Bearbeitungsvermerke when enum sonstige anywhere
eclipse-set/set pull request #676
Opened 2024-06-18 06:46 UTC by mariusheine

2024-06-18 11:12 UTC, TruongQuangSB commented
I think, u can filter _BasisAttribut_AttributeGroup_ by _allContents_, then find function _getWert_ with method _declaredMethods_ from Class and u can check, if the _Wert_ is _Enumerator_ or not. By that u don't need a List from BasisObject, which contains Enumerator

2024-06-19 07:39 UTC, TruongQuangSB commented
In addition we prefer to implement in Java instead of Xtext because we want to gradually move away from Xtext

2024-06-20 06:03 UTC, pstuecker requested changes

2024-06-20 06:03 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.plazmodel/src/org/eclipse/set/feature/plazmodel/check/SonstigeRequiresBearbeitungsvermerk.xtend
> +		new Check(Aussenelementansteuerung, [ aussenElementAnsteuerungArt ], "aussenelementansteuerungArt"),
Listing all possible types with enumerations here seems like a rather tedious task.

My suggestion would be to iterate all elements (eAllContents) and then filter for entries with a value that has an `eClass` that is an `EEnum`. That way we can identify every enumeration value in the planning file.

For those set to a Sonstige value, we can then go back up the EMF parent chain until we find the containing 
`Ur_Objekt` and check it for a remark.

2024-06-20 07:32 UTC, mariusheine commented on java/bundles/org.eclipse.set.feature.plazmodel/src/org/eclipse/set/feature/plazmodel/check/SonstigeRequiresBearbeitungsvermerk.xtend
> +		new Check(Aussenelementansteuerung, [ aussenElementAnsteuerungArt ], "aussenelementansteuerungArt"),
@pstuecker This does not work. the `eClass` is never an instance of or equal to `EEnum`.

I try it now with the idea of @TruongQuangSB  https://github.com/eclipse-set/set/pull/676#issuecomment-2175843950

2024-06-20 22:57 UTC, mariusheine commented on java/bundles/org.eclipse.set.feature.plazmodel/src/org/eclipse/set/feature/plazmodel/check/SonstigeRequiresBearbeitungsvermerk.xtend
> +			return it.singleRun(modelSession.planProSchnittstelle.eAllContents)
Changed it java class so this doesn't matter anymore

2024-06-20 22:58 UTC, mariusheine commented on java/bundles/org.eclipse.set.feature.plazmodel/src/org/eclipse/set/feature/plazmodel/check/SonstigeRequiresBearbeitungsvermerk.xtend
> +		new Check(Aussenelementansteuerung, [ aussenElementAnsteuerungArt ], "aussenelementansteuerungArt"),
This works now nicely with a combined way

2024-06-20 22:59 UTC, mariusheine commented
@pstuecker I also tried to achieve this grouping of errors like for the "Teilbereichsgrenzen" but was not able to achieve this. Maybe you can give me a hint on how to do this

2024-06-21 05:17 UTC, pstuecker commented
It actually already works, it just doesn't show up in PHausen, as groups are only created if all fields (excluding row number, line number and message) are equal, and there are at least 5 elements in the group. In PHausen all groups are of size 4 or less.

2024-06-21 05:17 UTC, pstuecker approved these changes

2024-06-21 05:17 UTC, merged