Ssza: Initial draft implementation
eclipse-set/set pull request #710
Opened 2024-06-26 11:18 UTC by pstuecker

2024-06-28 08:33 UTC, TruongQuangSB requested changes

2024-06-28 08:33 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.feature.table.pt1/src/org/eclipse/set/feature/table/pt1/ssza/SszaTransformator.xtend
> +						flatten
```suggestion
					val pos = #[]
					sue.forEach [
						switch (it) {
							Zugeinwirkung,
							FMA_Komponente:
								pos.addAll(punktObjektStrecke)
							FMA_Anlage: {
								val fmaKomponente = container.FMAKomponente.filter[IDFMAgrenze.contains(it)]
								pos.addAll(fmaKomponente.flatMap[punktObjektStrecke])		
							}	
						}
					]
```
here could be use switch in for loop too avoid loop _sue_ 3 times and easier to understand

2024-06-28 08:33 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.feature.table.pt1/src/org/eclipse/set/feature/table/pt1/ssza/SszaTransformator.xtend
> +					return pos
```suggestion
					return sue.flatMap[
						switch(it) {
							Zugeinwirkung,
							FMA_Komponente:
								return getKMStrecke.apply(it)
							// TODO FMA_Anlage
						}
						return null
					].filterNull
```
same here

2024-06-28 08:33 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.feature.table.pt1/src/org/eclipse/set/feature/table/pt1/ssza/SszaTransformator.xtend
> +		fillFootnotes(datenpunkt)
```suggestion
		// O: Ssza.Bemerkung
		fillFootnotes(datenpunkt)
```
duplicated

2024-07-01 13:01 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.table.pt1/src/org/eclipse/set/feature/table/pt1/ssza/SszaTransformationService.java
> +		extends AbstractPlanPro2TableTransformationService {
the provided sorting priority does not make any sense

2024-07-01 14:06 UTC, TruongQuangSB approved these changes

2024-07-01 14:08 UTC, TruongQuangSB approved these changes

2024-07-01 14:09 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.feature.table.pt1/src/org/eclipse/set/feature/table/pt1/ssza/SszaTransformator.xtend
> +		TMFactory factory) {
```suggestion
	override transformTableContent(MultiContainer_AttributeGroup container,
		TMFactory factory, Stell_Bereich controlArea) {
```

2024-07-01 14:10 UTC, TruongQuangSB requested changes
Build error

2024-07-02 07:21 UTC, TruongQuangSB approved these changes

2024-07-02 07:21 UTC, merged