Update Table Sskp
eclipse-set/set pull request #73
Opened 2023-09-13 15:40 UTC by TruongQuangSB

- Update Enumerator file
- Update Table Sskp

2023-09-13 15:41 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.utils/src/org/eclipse/set/utils/graph/DigraphExtensions.xtend
move to Digrahp class

2023-09-14 04:14 UTC, pstuecker requested changes

2023-09-14 04:14 UTC, pstuecker commented on java/bundles/org.eclipse.set.core/translation/Enumerators.properties
> +XSBoolean_false_Presentation=nein
```suggestion
XSBoolean_false_Presentation=□
```

2023-09-14 04:14 UTC, pstuecker commented on java/bundles/org.eclipse.set.core/translation/Enumerators.properties
> +XSBoolean_true_Presentation=ja
```suggestion
XSBoolean_true_Presentation=x
```

2023-09-14 07:28 UTC, pstuecker approved these changes

2023-09-14 07:28 UTC, merged