Add zero width space for line break
eclipse-set/set pull request #792
Opened 2024-08-05 16:01 UTC by TruongQuangSB

**Titlebox by field _Bauzustand Zeichen_**:
 - Add _zero width space_ to long text without space  to automatic line break

2024-08-06 09:46 UTC, mariusheine requested changes

2024-08-06 09:46 UTC, mariusheine commented on java/bundles/org.eclipse.set.ppmodel.extensions/src/org/eclipse/set/ppmodel/extensions/utils/PlanProToTitleboxTransformation.xtend
> +			}
@TruongQuangSB I have added the following value for the `BauzustandKurzbezeichnung`: `wwwwwwwwwwwwwwwwwwwwwww` 

This led to the following issues:
- 9 characters for the max length is insufficient because 9 times `w` is already too wide
- if external tools are sending more than 15 letters we need a third line

As a solution I would suggest to do:
bauzustand.split(' ').map(word -> // insert ZERO_WIDTH_SPACE at every 7th character )

2024-08-06 09:46 UTC, mariusheine commented on java/bundles/org.eclipse.set.ppmodel.extensions/src/org/eclipse/set/ppmodel/extensions/utils/PlanProToTitleboxTransformation.xtend
> +			}
![image](https://github.com/user-attachments/assets/c97d1e4a-0486-4e98-8112-e92278ab58da)

2024-08-06 10:37 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.ppmodel.extensions/src/org/eclipse/set/ppmodel/extensions/utils/PlanProToTitleboxTransformation.xtend
> +			}
ok, i have change max length text to 7. The text shouldn't have more than 15 character. We have a pattern for check this

2024-08-08 12:25 UTC, mariusheine commented on java/bundles/org.eclipse.set.ppmodel.extensions/src/org/eclipse/set/ppmodel/extensions/utils/PlanProToTitleboxTransformation.xtend
> +			}
@TruongQuangSB Perfect

2024-08-08 12:25 UTC, mariusheine approved these changes

2024-08-08 12:25 UTC, mariusheine approved these changes

2024-08-08 12:28 UTC, merged