Complete Ssza Transformator
eclipse-set/set pull request #807
Opened 2024-08-09 14:12 UTC by TruongQuangSB

- Required PR #705

2024-08-28 09:58 UTC, TruongQuangSB commented
Fixes sub-plan/link#2

2024-09-19 12:17 UTC, mariusheine requested changes

2024-09-19 12:17 UTC, mariusheine commented on java/bundles/org.eclipse.set.ppmodel.extensions/src/org/eclipse/set/ppmodel/extensions/StreckePunktExtensions.xtend
> +
```suggestion
```

2024-09-19 12:40 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.feature.table.pt1/src/org/eclipse/set/feature/table/pt1/ssza/SszaTransformator.xtend
> +					// TODO
@mariusheine the logic still not clear

2024-09-19 12:44 UTC, mariusheine approved these changes

2024-09-19 13:01 UTC, merged