implementationn Sszs - Muka Signal
eclipse-set/set pull request #890
Opened 2024-09-20 13:43 UTC by TruongQuangSB

2024-10-10 08:42 UTC, pstuecker requested changes

2024-10-10 08:42 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.table.pt1/src/org/eclipse/set/feature/table/pt1/sszs/SszsTransformator.xtend
> +					["sLs"]
```suggestion
					["Ls"]
```

2024-10-10 08:42 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.table.pt1/src/org/eclipse/set/feature/table/pt1/sszs/SszsTransformator.xtend
> +					(ETCSSignalTBV?.TBVTunnelbereichLaenge?.wert ?: "").toString
This should be rounded up to an integer

2024-10-10 08:42 UTC, pstuecker commented on java/bundles/org.eclipse.set.feature.table.pt1/src/org/eclipse/set/feature/table/pt1/sszs/SszsTransformator.xtend
> +				new Case<Signal>(
If both cases apply, both should be returned

2024-10-10 09:38 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.feature.table.pt1/src/org/eclipse/set/feature/table/pt1/sszs/SszsTransformator.xtend
> +					["sLs"]
Why? In this case should fill 'sLs'

2024-10-11 09:51 UTC, sbx320 approved these changes

2024-10-11 09:52 UTC, pstuecker approved these changes

2024-10-11 09:52 UTC, merged