Issue/nattable grouping same row
eclipse-set/set pull request #90
Opened 2023-09-27 08:33 UTC by TruongQuangSB

- Grouping same problem content in validation- and plazmodel view
- By default will all grouping collapsed
- Configuration minimun element of a group in config.ini with parameter : toolbox.table.tree.minimum

2023-09-27 08:39 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.utils.table/src/org/eclipse/set/utils/table/sorting/AbstractSortByColumnTables.java
> +				sortModel, sortHeaderLayer, treeLayer));
unregister default commandhandler and add custom handler

2023-10-12 06:30 UTC, pstuecker requested changes

2023-10-12 06:30 UTC, pstuecker commented on pom.xml
> +				<version>2.32.0</version>
```suggestion
				<version>2.27.0</version>
```
Xtend requires Xtend libs, which aren't updated yet (as they depend on a new Eclipse platform).

2023-10-12 09:07 UTC, TruongQuangSB commented on pom.xml
> +				<version>2.32.0</version>
ok, i have upgrade,  because 2.27 version not working with default function in interface. Now I have IMPROVE for this default function notice

2023-10-12 09:43 UTC, pstuecker approved these changes

2023-10-12 09:43 UTC, merged