Modify condition for object in control area
eclipse-set/set pull request #983
Opened 2024-10-16 16:24 UTC by TruongQuangSB

The following belongs to control area condition has been adjusted:
- _Gleis_Bezeichnung_
- _Gleis_Abschnitt_
- _FMA_Anlage_
- _FstrAneiander_

2024-10-16 16:26 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.ppmodel.extensions/src/org/eclipse/set/ppmodel/extensions/GleisAbschnittExtensions.xtend
> -	}
Use _BreichObjektExtensions.getOverlappinglength_ instead

2024-10-16 16:27 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.ppmodel.extensions/src/org/eclipse/set/ppmodel/extensions/FmaAnlageExtensions.xtend
> -	}
Check direct in _StellbreichExtensions_

2024-10-28 22:14 UTC, mariusheine requested changes

2024-10-28 22:14 UTC, mariusheine commented on java/bundles/org.eclipse.set.ppmodel.extensions/src/org/eclipse/set/ppmodel/extensions/StellBereichExtensions.java
> +				area, description, 50);
@TruongQuangSB These two cases have swapped. Was this intentional?

2024-10-28 22:14 UTC, mariusheine commented on java/bundles/org.eclipse.set.ppmodel.extensions/src/org/eclipse/set/ppmodel/extensions/StellBereichExtensions.java
@TruongQuangSB I don't like the comments above each case because it is redundant. You can easily see what entity is handled by `case final <class>`. SO I think we can remove them again.

2024-10-28 22:14 UTC, mariusheine commented on java/bundles/org.eclipse.set.ppmodel.extensions/src/org/eclipse/set/ppmodel/extensions/StellBereichExtensions.java
@TruongQuangSB I don't like the comments above each case because it is redundant. You can easily see what entity is handled by `case final <class>`. SO I think we can remove them again.

2024-10-29 09:11 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.ppmodel.extensions/src/org/eclipse/set/ppmodel/extensions/StellBereichExtensions.java
> +				area, description, 50);
@TruongQuangSB it isn't 😄

2024-10-29 09:18 UTC, mariusheine commented on java/bundles/org.eclipse.set.ppmodel.extensions/src/org/eclipse/set/ppmodel/extensions/StellBereichExtensions.java
> +				area, description, 50);
@TruongQuangSB But previouly we had this `BereichtObjectExtenions.intersects(...` for the `Gleisbezeichnung` and now it is at `Gleisabschnitt`

2024-10-29 09:33 UTC, TruongQuangSB commented on java/bundles/org.eclipse.set.ppmodel.extensions/src/org/eclipse/set/ppmodel/extensions/StellBereichExtensions.java
> +				area, description, 50);
@mariusheine ah. I have misunderstanding. This is intentional, because it give the case, that need only the `Gleis_Abschnitt` intersect the area and by `Gleis_Bezeichnung` is fixed to over 50% overlapp

2024-10-29 09:37 UTC, mariusheine approved these changes

2024-10-29 10:09 UTC, merged